const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const wiki = fs.readFileSync(path.join(__dirname, '..', 'wikipedia.js'), 'utf8');
const names = fs.readFileSync(path.join(__dirname, '..', 'local-name-search.js'), 'utf8');
const html = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8');
assert.match(wiki, /normalizeTaxon/, 'taxon comparison normalizes hybrid symbol');
assert.match(wiki, /P225/, 'Wikipedia article is tied to exact scientific taxon');
assert.match(wiki, /commonNameForScientific/, 'common name uses local names');
assert.match(wiki, /enrichCard\(card, name\)/, 'Wikipedia details appear on result cards automatically');
assert.match(wiki, /article\.extract/, 'Wikipedia summary is rendered');
assert.match(names, /'fragaria x ananassa': 'תות שדה'/, 'strawberry common name is available');
assert.match(html, /wikipedia\.js\?v=22/, 'fresh Wikipedia script loaded');
console.log('PASS common names and Wikipedia cards contract');
